# Docling уже внутри — не дублируем
FROM rag_qdrant-docling:latest

USER root

RUN pip install --no-cache-dir \
    "pendulum<3" \
    "Flask-Session<0.7" \
    "connexion<3.0" \
    apache-airflow==2.7.1 \
    apache-airflow-providers-postgres \
    && useradd -m -u 50000 airflow \
    && mkdir -p /opt/airflow \
    && chown -R airflow:airflow /opt/airflow

ENV AIRFLOW_HOME=/opt/airflow
ENV AIRFLOW_UID=50000

USER airflow
WORKDIR /opt/airflow
