FROM apache/airflow:2.7.1-python3.10

USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libgl1-mesa-glx \
    libglib2.0-0 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

USER airflow
COPY requirements-ingest.txt .
RUN uv pip install --no-cache -r requirements-ingest.txt